query ListProducts{
      allProduct {
        _id
        ,name,
        slug{
          current
        },
        price,
        image {
          asset {
            url
          }
        },
        description,
       gender {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        },
        sub_category
       
       
        
      }
    }

query ListProductsByCategoryAndGender($category:String!,$gender:String!){
    allProduct(where : {category :{slug: {current: {eq: $category}} }, gender:{slug: {current: {eq: $gender}} }} ){
        _id
        ,name,
        slug{
          current
        },
        price,
        image {
          asset {
            url
          }
        },
        description,
       gender{
         _id,
          name,
          slug{
            current
          }
       }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        sub_category
    }
}

query ListProductsByCategory($category:String!){
    allProduct(where : {category :{slug: {current: {eq: $category}} }} ){
        _id
        ,name,
        slug{
          current
        },
        price,
        image {
          asset {
            url
          }
        },
        description,
       gender{
         _id,
          name,
          slug{
            current
          }
       }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        sub_category
    }
}

query ListProductsByGender($slug:String!){
    allProduct(where : {gender :{slug: {current: {eq: $slug}} }} ){
        _id
        ,name,
        slug{
          current
        },
        price,
        image {
          asset {
            url
          }
        },
        description,
       
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
    }
}