query ListProducts{
      allProduct {
        _id
        ,name,
        slug{
          current
        },
        price,
        images {
          asset {
            url
          }
        },
        description,
       gender {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        },
        sub_category,
        size{
          name,value
        },
        color
       
       
        
      }
    }

query ListProductsByCategoryAndGender($category:String!,$gender:String!){
    allProduct(where : {category :{slug: {current: {eq: $category}} }, gender:{slug: {current: {eq: $gender}} }} ){
        _id
        ,name,
        slug{
          current
        },
        price,
        images {
          asset {
            url
          }
        },
        description,
       gender{
         _id,
          name,
          slug{
            current
          }
       }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        sub_category,size{
          name,value
        },color
    }
}

query ListProductsByCategory($category:String!){
    allProduct(where : {category :{slug: {current: {eq: $category}} }} ){
        _id
        ,name,
        slug{
          current
        },
        price,
        images {
          asset {
            url
          }
        },
        description,
       gender{
         _id,
          name,
          slug{
            current
          }
       }
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        }
        sub_category,
        size{
          name,value
        },color
    }
}

query ListProductsBySearch($searchterm:String!){
    allProduct(where : {name :{matches: $searchterm}}  ){
        _id
        ,name,
        slug{
          current
        },
        price,
        gender{
          _id 
          name
          slug{
            current
          }
        }
        images {
          asset {
            url
          }
        },
        description,
       sub_category
        category {
          _id,
          name
          ,
          slug{
            current
          }
         
        },
        color
    }
}